volumes:
  db-dev:

networks:
  databased:
    driver: bridge
  filesystem:
    driver: bridge

services:
  database:
    image: mysql
    container_name: archecode-mysql-database
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-db}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-password!}
      MYSQL_USER: ${USER:-user}
      MYSQL_PASSWORD: ${PASSWORD:-password}
    volumes:
      - db-dev:/var/lib/mysql
    networks:
      - databased

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - databased
      - filesystem
    ports:
      - "8080:8080"
  
  filecloud:
    image: minio
    container_name: archecode-minio
    environment:
      MINIO_ROOT_USER=admin
      MINIO_ROOT_PASSWORD=password
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - filesystem
