volumes:
  db-dev:

networks:
  databased:
    driver: bridge
  filesystem:
    driver: bridge

services:
  database:
    image: mysql
    container_name: archecode-mysql-database
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-db}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-password!}
      MYSQL_USER: ${USER:-user}
      MYSQL_PASSWORD: ${PASSWORD:-password}
    volumes:
      - db-dev:/var/lib/mysql
    networks:
      - databased

  # backend:
  #   container_name: archecode-backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - database
  #   networks:
  #     - databased
  #     - filesystem
  #   ports:
  #     - "8080:8080"

  filecloud:
    image: versity/versitygw:v1.8.0
    container_name: archecode-filecloud
    environment:
      ROOT_ACCESS_KEY: ${S3_ACCESS_KEY:-s3user}
      ROOT_SECRET_KEY: ${S3_SECRET_KEY:-s3password}
    volumes:
      - ./data/filecloud:/data/s3
      - ./data/iam:/data/iam
    command: [
      "--webui", ":7071",
      "--cors-allow-origin", "http://127.0.0.1:7071",
      "--iam-dir", "/data/iam",
      "posix", "/data/s3"
    ]
    ports:
      - "7070:7070" #s3
      - "7071:7071" #ui
    restart: always
    networks:
      - filesystem
