import type { Metadata } from 'next';
import './css/globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={`h-full antialiased`}>
            <body className="min-h-full flex flex-col relative">
                <div>{modal}</div>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
