debug: ${DEBUG_ENABLED}
spring:
  application:
    name: archecode
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: ${DEBUG_ENABLED}
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${REFRESH_EXPIRATION}
