debug: false
spring:
    application:
        name: archecode
    flyway:
        enabled: true
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: validate
    main:
        allow-bean-definition-overriding: true
    datasource:
      url: jdbc:mysql://localhost:3306/db
      username: root
      password: password!

server:
  port: 8080

jwt:
    secret: secret-key-min-32-symbols-but-better-256-so-please-be-careful-with-this
    expiration: 900000
    refresh:
      expiration: 259200000
